name: ClaudeMon
options:
  bundleIdPrefix: com.claudemon
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"

targets:
  ClaudeMon:
    type: application
    platform: macOS
    sources:
      - path: ClaudeMon
    settings:
      base:
        INFOPLIST_FILE: ClaudeMon/Info.plist
        CODE_SIGN_ENTITLEMENTS: ClaudeMon/ClaudeMon.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.jfluhler.claudemonitor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_APP_SANDBOX: false
        ENABLE_HARDENED_RUNTIME: true
        PRODUCT_NAME: ClaudeMonitor
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        COMBINE_HIDPI_IMAGES: true
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
